/* Generated By:JJTree: Do not edit this line. .\PascalSpimTreeConstants.java */

public interface PascalSpimTreeConstants
{
  public int JJTPROGRAMSTART = 0;
  public int JJTVOID = 1;
  public int JJTFUNCTIONBLOCK = 2;
  public int JJTPROCEDUREBLOCK = 3;
  public int JJTBLOCK = 4;
  public int JJTFACTOR = 5;
  public int JJTTERM = 6;
  public int JJTSIMPEXPRESSION = 7;
  public int JJTEXPRESSION = 8;
  public int JJTSTATEMENT = 9;
  public int JJTCASESEQUENCE = 10;


  public String[] jjtNodeName = {
    "programStart",
    "void",
    "functionBlock",
    "procedureBlock",
    "block",
    "factor",
    "term",
    "simpExpression",
    "expression",
    "statement",
    "caseSequence",
  };
}
