/* Generated By:JJTree: Do not edit this line. .\PascalSpimTreeConstants.java */

public interface PascalSpimTreeConstants {
    int JJTPROGRAMSTART = 0;
    int JJTVOID = 1;
    int JJTFUNCTIONBLOCK = 2;
    int JJTPROCEDUREBLOCK = 3;
    int JJTBLOCK = 4;
    int JJTFACTOR = 5;
    int JJTTERM = 6;
    int JJTSIMPEXPRESSION = 7;
    int JJTEXPRESSION = 8;
    int JJTSTATEMENT = 9;
    int JJTCASESEQUENCE = 10;


    String[] jjtNodeName = {
            "programStart",
            "void",
            "functionBlock",
            "procedureBlock",
            "block",
            "factor",
            "term",
            "simpExpression",
            "expression",
            "statement",
            "caseSequence",
    };
}
