/* Generated By:JavaCC: Do not edit this line. PascalSpimConstants.java */
public interface PascalSpimConstants {

    int EOF = 0;
    int PROGRAM = 11;
    int BEGIN = 12;
    int END = 13;
    int IF = 14;
    int THEN = 15;
    int ELSE = 16;
    int WHILE = 17;
    int CASE = 18;
    int OF = 19;
    int DO = 20;
    int FUNCTION = 21;
    int PROCEDURE = 22;
    int VAR = 23;
    int CONST = 24;
    int TYPE = 25;
    int TRUE = 26;
    int FALSE = 27;
    int EOS = 28;
    int COMMA = 29;
    int COLON = 30;
    int DDOT = 31;
    int DOT = 32;
    int OP_BRAC = 33;
    int CL_BRAC = 34;
    int OP_PAR = 35;
    int CL_PAR = 36;
    int PLUS = 37;
    int MINUS = 38;
    int MULT = 39;
    int DIV = 40;
    int MOD = 41;
    int DIVR = 42;
    int AND = 43;
    int OR = 44;
    int NOT = 45;
    int ASSIGN = 46;
    int LT = 47;
    int GT = 48;
    int EQ = 49;
    int LET = 50;
    int GET = 51;
    int NE = 52;
    int INTEGER = 53;
    int REAL = 54;
    int BOOLEAN = 55;
    int CHAR = 56;
    int ARRAY = 57;
    int LETTER = 58;
    int DIGIT = 59;
    int ID = 60;
    int UNS_INT = 61;
    int UNS_NUM = 62;
    int STLIT = 63;

    int DEFAULT = 0;
    int INSIDE_COMMENT_1 = 1;
    int INSIDE_COMMENT_2 = 2;

    String[] tokenImage = {
            "<EOF>",
            "\" \"",
            "\"\\t\"",
            "\"\\n\"",
            "\"\\r\"",
            "\"(*\"",
            "\"{\"",
            "\"*)\"",
            "<token of kind 8>",
            "\"}\"",
            "<token of kind 10>",
            "\"program\"",
            "\"begin\"",
            "\"end\"",
            "\"if\"",
            "\"then\"",
            "\"else\"",
            "\"while\"",
            "\"case\"",
            "\"of\"",
            "\"do\"",
            "\"function\"",
            "\"procedure\"",
            "\"var\"",
            "\"const\"",
            "\"type\"",
            "\"true\"",
            "\"false\"",
            "\";\"",
            "\",\"",
            "\":\"",
            "\"..\"",
            "\".\"",
            "\"[\"",
            "\"]\"",
            "\"(\"",
            "\")\"",
            "\"+\"",
            "\"-\"",
            "\"*\"",
            "\"div\"",
            "\"mod\"",
            "\"/\"",
            "\"and\"",
            "\"or\"",
            "\"not\"",
            "\":=\"",
            "\"<\"",
            "\">\"",
            "\"=\"",
            "\"<=\"",
            "\">=\"",
            "\"<>\"",
            "\"integer\"",
            "\"real\"",
            "\"boolean\"",
            "\"char\"",
            "\"array\"",
            "<LETTER>",
            "<DIGIT>",
            "<ID>",
            "<UNS_INT>",
            "<UNS_NUM>",
            "<STLIT>",
            "<token of kind 64>",
    };

}
